spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todo
    driver-class-name: org.h2.Driver
    username:
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        show_sql: true


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
