spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todo
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
